#!/bin/bash

# Set options
ROOT_FOLDER=".."
CMAKE_BUILD_TYPE=Debug
CMAKE_CXX_COMPILER=clang++

# Build tests
cmake -S $ROOT_FOLDER -B $ROOT_FOLDER/build/$CMAKE_BUILD_TYPE \
    -DCMAKE_CXX_COMPILER=$CMAKE_CXX_COMPILER \
    -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE \
    -DINC_BETA_BUILD_TESTS=ON \
    -DCMAKE_CXX_FLAGS="-m64 -Wall -pedantic"
cmake --build $ROOT_FOLDER/build/$CMAKE_BUILD_TYPE --parallel 6

# Run tests
cd $ROOT_FOLDER/build/$CMAKE_BUILD_TYPE
ctest
cd ../..